### ISSUE TITLE
Explain Instance - Note that this assumes that the classifier was trained with inputs normalized in [-0.5,0.5] range.

### ISSUE THREAD

**Issue by jrinvictus** [IBM/AIX360#52]
There is a note on the explain_instance function that states:
```Note that this assumes that the classifier was trained with inputs normalized in [-0.5,0.5] range.```

Is there a reason this is required and we can not use a different normalization range?

**Comment by sadhamanus** [comment]
Hi jrinvictus, It is just the normalization we have chosen for some of our explainability algorithms like cem. The projection operators in the code assume that. So if you do use a different normalization you will also have to make changes at the appropriate places in the code of these methods.
