### ISSUE TITLE
CEMExplainer with scikit-learn Models

### ISSUE THREAD

**Issue by shlomihod** [IBM/AIX360#87]
Does CEMExplainer support scikit-learn models (e.g., RandomForestClassifier)?

**Comment by sadhamanus** [comment]
The CEM explainer in the toolkit is not model agnostic and so requires a differentiable model to work. We have a model agnostic version in Watson Openscale (IBM product) which works with arbitrary classifiers.

**Comment by shlomihod** [comment]
Thanks!
