### ISSUE TITLE
Protodash

### ISSUE THREAD

**Issue by firmai** [IBM/AIX360#88]
Is the benefit of protodash that the data does not have to be normalised? And the other one that you get weights. I am just trying to understand why one should use protodash and not a nearest neighbour algorithm. Thanks in advance.

**Comment by sadhamanus** [comment]
So if you look at the FICO and Healthcare tutorials you will see that Protodash can be used in multiple ways such as to explain a single data point or find representative points from a dataset. Not sure how NN can be used for the second scenario. Even for the first scenario the key difference is that Protodash will pick data points that are representative but also diverse. The diversity aspect is useful as there maybe different ways why the data point to be explained might have the specific predictions. A NN approach wont have that as it might pick data points that are extremely similar to not the data point to be explained but also each other. For further details please look at the paper.

**Comment by firmai** [comment]
That is excellent thanks.
