### ISSUE TITLE
ProtoDash: local variable 'newinnerProduct' referenced before assignment

### ISSUE THREAD

**Issue by laramdemajo** [IBM/AIX360#90]
I am using the HELOC Dataset and trying to explain a single test instance using prototypes from my training subset using below code:

`explainer = ProtodashExplainer()`
`(W, S, _) = explainer.explain(dfTrain.to_numpy(), dfTest.iloc[0:1,:].to_numpy(), m=2)`

However, I am getting below error:
<img width="918" alt="Screen Shot 2020-05-22 at 01 58 42" src="https://user-images.githubusercontent.com/23550363/82617253-c8f11600-9bcf-11ea-8809-658263dc8e5f.png">

Is this intentional? Please help. 

Thank you

**Comment by laramdemajo** [comment]
Hi I would really appreciate some feedback please. I am using this library for my disseration and currently stuck due to this issue. Your help will be very much appreciated.

**Comment by ArpitSisodia** [comment]
I doubt you can use prototype for single instance. It is a way of sampling the data. Does it make sense to sample single instance ?

**Comment by laramdemajo** [comment]
It should be possible, because IBM's Arya et al. state in their paper that ProtoDash can be used to explain a single test sample using samples from the train set (https://arxiv.org/pdf/1909.03012.pdf).

> ProtoDash [26]: Selects diverse and representative samples that summarize a dataset or explain a test instance. Non-negative importance weights are also learned for each of the selected samples.

**Comment by sadhamanus** [comment]
So you can explain a single instance but the dataset you use to explain it has to have multiple instances. You cannot have both X and Y have cardinality 1.

**Comment by laramdemajo** [comment]
Of course, in fact in my code `dfTrain` contains 7403 instances as shown below:
<img width="886" alt="Screen Shot 2020-05-27 at 15 50 30" src="https://user-images.githubusercontent.com/23550363/83028531-daa04680-a031-11ea-9b8c-235a6638636f.png">

**Comment by sadhamanus** [comment]
So then try swapping the arguments. The thing to be explained is to come first. Also check they have the same dimensionality.

**Comment by laramdemajo** [comment]
Many thanks for your help. Swapping the arguments did the trick. 

I followed the below comments in the PDASH.py file of this library so maybe you need to change the explanation there to avoid anyone doing the same mistake.

<img width="544" alt="Screen Shot 2020-05-27 at 16 18 28" src="https://user-images.githubusercontent.com/23550363/83032311-f4438d00-a035-11ea-8b6f-05ad1db100b6.png">

**Comment by sadhamanus** [comment]
Awesome! Thanks.
